//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlinesReservationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCard
    {
        public string CCNo { get; set; }
        public string CVV { get; set; }
        public string OwnerName { get; set; }
        public double Balance { get; set; }
    }
}
