//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlinesReservationSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Route
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Route()
        {
            this.Flight = new HashSet<Flight>();
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int RNo { get; set; }

        [Required]
        [StringLength(10)]
        [Display(Name ="Route's Airline")]
        public string RAirline { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Route's Aircraft")]
        public string RAircraft { get; set; }

        [Required]
        [StringLength(10)]
        public string Departure { get; set; }

        [Required]
        [StringLength(10)]
        public string Destination { get; set; }
    
        public virtual Aircraft Aircraft { get; set; }
        public virtual Airline Airline { get; set; }
        public virtual Airport DepartureAirport { get; set; }
        public virtual Airport DestinationAirport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flight> Flight { get; set; }
    }
}
