//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlinesReservationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Route()
        {
            this.Flight = new HashSet<Flight>();
        }
    
        public int RNo { get; set; }
        public string RAirline { get; set; }
        public string RAircraft { get; set; }
        public Nullable<int> AvailSeatsF { get; set; }
        public Nullable<int> AvailSeatsB { get; set; }
        public int AvailSeatsE { get; set; }
        public string Departure { get; set; }
        public string Destination { get; set; }
    
        public virtual Aircraft Aircraft { get; set; }
        public virtual Airline Airline { get; set; }
        public virtual Airport Airport { get; set; }
        public virtual Airport Airport1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flight> Flight { get; set; }
    }
}
