//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlinesReservationSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.TicketService = new HashSet<TicketService>();
        }

        [Required]
        [Key]
        [RegularExpression("S\\d{2}")]
        [Display(Name ="Service ID")]
        public string ServiceID { get; set; }

        [Required]
        [StringLength(50, MinimumLength = 3)]
        [Display(Name = "Service Name")]
        public string ServiceName { get; set; }

        [Display(Name = "Service Details")]
        public string ServiceDetails { get; set; }

        [Required]
        [Display(Name = "Service Fee")]
        [Range(5,10000)]
        public double ServiceFee { get; set; }

        [Required]
        [Display(Name = "Service Active")]
        public bool IsServing { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketService> TicketService { get; set; }
    }
}
