//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlinesReservationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.TicketService = new HashSet<TicketService>();
        }
    
        public long TicketID { get; set; }
        public long OrderID { get; set; }
        public string FNo { get; set; }
        public string PassportNo { get; set; }
        public string Class { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public bool Sex { get; set; }
        public int Age { get; set; }
        public bool IsReturn { get; set; }
        public double Price { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketService> TicketService { get; set; }
    }
}
